#!/bin/bash
# Debian Initiation Program
# Copyright (c) 2024 By Marvin.W

# Update Kernel:
apt update
apt install -y linux-image-amd64/stable-backports linux-headers-amd64/stable-backports

# Configurate GRUB to Enable Serial Port (console=ttyS0,115200 |console=tty0)
# So the Copy and PasteCan be Available under xterm.js
# Configurate Debian System:
dpkg-reconfigure locales
sed -i 's|GRUB_TIMEOUT=5|GRUB_TIMEOUT=1|g' /etc/default/grub
#sed -i '/GRUB_CMDLINE_LINUX_DEFAULT/s/"quiet"/"quiet console=ttyS0,115200"/' /etc/default/grub
sed -i 's|#GRUB_GFXMODE|GRUB_GFXMODE|' /etc/default/grub
update-grub

sed -i 's#http://deb.debian.org#https://mirrors.huaweicloud.com#g' /etc/apt/sources.list
sed -i 's#http://security.debian.org/debian-security#https://mirrors.huaweicloud.com/debian-security#g' /etc/apt/sources.list

apt update
apt upgrade -y
apt install -y bash-completion \
gnome-core gnome-shell desktop-base \
network-manager-gnome gnome-audio gnome-clocks gnome-shell-extension-prefs gnome-shell-extension-dashtodock gnome-keyring gnome-remote-desktop gnome-shell-extension-appindicator yaru-theme-gnome-shell gnome-shell-extension-desktop-icons-ng \
policykit-1 policykit-1-gnome power-profiles-daemon fwupd-amd64-signed fwupd \
ssh sudo --no-install-recommends
# Spare hardware driver:firmware-amd-graphics firmware-misc-nonfree firmware-linux-nonfree va-driver-all

apt remove -y gnome-contacts
apt autoremove -y
apt autopurge -y
sed -i 'N;$!P;$!D;$d' /etc/network/interfaces

exit 0
