#!/bin/bash
# Debian Initiation Program
# Copyright (c) 2024 By Marvin.W

# Update Kernel:
apt update
apt install -y linux-image-amd64/stable-backports linux-headers-amd64/stable-backports

# Configurate GRUB to Enable Serial Port (console=ttyS0,115200 |console=tty0)
# So the Copy and PasteCan be Available under xterm.js
# Configurate Debian System:
dpkg-reconfigure locales
sed -i 's|GRUB_TIMEOUT=5|GRUB_TIMEOUT=1|g' /etc/default/grub
#sed -i '/GRUB_CMDLINE_LINUX_DEFAULT/s/"quiet"/"quiet console=ttyS0,115200"/' /etc/default/grub
sed -i 's|#GRUB_GFXMODE|GRUB_GFXMODE|' /etc/default/grub
update-grub

echo "Waiting for 3 Seconds..."
sleep 3

sed -i 's#http://deb.debian.org#https://mirrors.huaweicloud.com#g' /etc/apt/sources.list
sed -i 's#http://security.debian.org/debian-security#https://mirrors.huaweicloud.com/debian-security#g' /etc/apt/sources.list
apt update
apt upgrade -y
apt install -y bash-completion \
gnome-core gnome-shell desktop-base \
network-manager-gnome gnome-audio gnome-clocks gnome-shell-extension-prefs gnome-shell-extension-dashtodock gnome-keyring gnome-remote-desktop gnome-shell-extension-appindicator yaru-theme-gnome-shell gnome-shell-extension-desktop-icons-ng \
policykit-1 policykit-1-gnome power-profiles-daemon fwupd-amd64-signed fwupd \
ssh sudo --no-install-recommends
# Spare hardware driver:firmware-amd-graphics firmware-misc-nonfree firmware-linux-nonfree va-driver-all

apt remove -y gnome-contacts
apt autoremove -y
# Purge Obsoleted Kernels:
apt autopurge -y
sed -i 'N;$!P;$!D;$d' /etc/network/interfaces

# Debian SSH Root Login and Gnome Automatic Login:
sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config
sed -i 's|#  AutomaticLoginEnable|AutomaticLoginEnable|g' /etc/gdm3/daemon.conf
sed -i '/AutomaticLoginEnable/i\AutomaticLogin=marvin' /etc/gdm3/daemon.conf

# Make sudo Nopassword Setting Avaliable to Non-privilege Users:
Sudo_Line=$(grep "%sudo" /etc/sudoers | tail -1)
echo $Sudo_Line
sed -i "s|$Sudo_Line|%sudo ALL=(ALL:ALL) NOPASSWD:ALL|g" /etc/sudoers
#awk '($1 ~ "%" && !/sudo/) {$2= $2 FS "NOPASSWD:"; print }' /etc/sudoers
sed -i '/privilege specification/a\marvin     ALL=(ALL:ALL) NOPASSWD:ALL' /etc/sudoers

# Configurate Bash Commands Line:
find /home /root -name '.bashrc' -type f | xargs sed -i "/HISTSIZE=/c\HISTSIZE=-1"
find /home /root -name '.bashrc' -type f | xargs sed -i "/HISTFILESIZE=/c\HISTFILESIZE=-1"

echo -e "\n" >> /home/*/.bashrc
echo alias ll="'ls -ahls --color=always'" >> /home/*/.bashrc
echo alias l="'ls -ahls --color=always'" >> /home/*/.bashrc

echo -e "\n" >> /root/.bashrc
echo alias ll="'ls -ahls --color=always'" >> /root/.bashrc
echo alias l="'ls -ahls --color=always'" >> /root/.bashrc

echo -e "\nalias ll='ls -ahls --color=always'\nalias l='ls -ahls --color=always'" >> /etc/profile

# Vim and Vim.Tiny Configuration Customizing:
cat <<-EOF >> /etc/vim/vimrc.tiny
# Copyright (c) 2024 By Marvin.W
set nu ts=4 autoindent hlsearch incsearch showmode showcmd showmatch ignorecase smartcase hidden mouse=a paste nocompatible nobackup noswapfile cursorline ruler wrap linebreak laststatus=2
hi cursorLine cterm=bold ctermbg=DarkGray ctermfg=NONE
EOF

cat <<-EOF >> /etc/vim/vimrc
# Copyright (c) 2024 By Marvin.W
set nu ts=4 autoindent hlsearch incsearch showmode showcmd showmatch ignorecase smartcase hidden mouse=a paste nocompatible nobackup noswapfile cursorline ruler wrap linebreak laststatus=2
hi cursorLine cterm=bold ctermbg=DarkGray ctermfg=NONE
EOF

exit 0
