#!/bin/bash
# Debian Initiation Program

sed -i 's|GRUB_TIMEOUT=5|GRUB_TIMEOUT=1|g' /etc/default/grub
update-grub
sed -i 's#http://deb.debian.org#https://mirrors.huaweicloud.com#g' /etc/apt/sources.list
sed -i 's#http://security.debian.org/debian-security#https://mirrors.huaweicloud.com/debian-security#g' /etc/apt/sources.list
dpkg-reconfigure locales

apt update
apt upgrade -y
apt install -y bash-completion \
gnome-core gnome-shell desktop-base \
network-manager-gnome gnome-audio gnome-clocks gnome-shell-extension-dashtodock gnome-shell-extension-prefs \
gnome-keyring policykit-1 policykit-1-gnome \
fcitx5 fcitx5-chinese-addons fcitx5-config-qt fonts-wqy-microhei fonts-wqy-zenhei xfonts-wqy \
ssh sudo vim expect --no-install-recommends
apt remove -y gnome-contacts
apt autoremove -y
sed -i 'N;$!P;$!D;$d' /etc/network/interfaces

# Debian SSH Root Login and Gnome Automatic Login:
sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config
sed -i 's|#  AutomaticLoginEnable|AutomaticLoginEnable|g' /etc/gdm3/daemon.conf
sed -i '/AutomaticLoginEnable/i\AutomaticLogin=marvin' /etc/gdm3/daemon.conf

# Make sudo Nopassword Setting Avaliable to Non-privilege Users:
Sudo_Line=$(grep "%sudo" /etc/sudoers | tail -1)
echo $Sudo_Line
sed -i "s|$Sudo_Line|%sudo ALL=(ALL:ALL) NOPASSWD:ALL|g" /etc/sudoers
#awk '($1 ~ "%" && !/sudo/) {$2= $2 FS "NOPASSWD:"; print }' /etc/sudoers
sed -i '/privilege specification/a\marvin     ALL=(ALL:ALL) NOPASSWD:ALL' /etc/sudoers

# Vim and Vim.Tiny Configuration Customizing:
cp -f /etc/skel/.bashrc ~/
echo -e '\n' >> ~/.bashrc
echo alias ll="'ls -ahls --color=always'" >> ~/.bashrc
echo alias l="'ls -ahls --color=always'" >> ~/.bashrc

cp -f /etc/skel/.bashrc /home/marvin/
echo -e '\n' >> /home/marvin/.bashrc
echo alias ll="'ls -ahls --color=always'" >> /home/marvin/.bashrc
echo alias l="'ls -ahls --color=always'" >> /home/marvin/.bashrc

echo -e '\n' >> /etc/vim/vimrc.tiny
echo -e '\n' >> /etc/vim/vimrc.tiny
echo set nu >> /etc/vim/vimrc.tiny
echo set ts=4 >> /etc/vim/vimrc.tiny
echo set autoindent >> /etc/vim/vimrc.tiny
echo set hlsearch >> /etc/vim/vimrc.tiny
echo set incsearch >> /etc/vim/vimrc.tiny
echo set showmode >> /etc/vim/vimrc.tiny
echo set showcmd >> /etc/vim/vimrc.tiny
echo set showmatch >> /etc/vim/vimrc.tiny
echo set ignorecase >> /etc/vim/vimrc.tiny
echo set smartcase >> /etc/vim/vimrc.tiny
echo set hidden >> /etc/vim/vimrc.tiny
echo set mouse=a >> /etc/vim/vimrc.tiny
echo set paste >> /etc/vim/vimrc.tiny
echo set nocompatible >> /etc/vim/vimrc.tiny
echo set nobackup >> /etc/vim/vimrc.tiny
echo set noswapfile >> /etc/vim/vimrc.tiny
echo hi cursorLine cterm=bold ctermbg=DarkGray ctermfg=NONE >> /etc/vim/vimrc.tiny
echo set cursorline >> /etc/vim/vimrc.tiny
echo set ruler >> /etc/vim/vimrc.tiny
echo set wrap >> /etc/vim/vimrc.tiny
echo set linebreak >> /etc/vim/vimrc.tiny
echo set laststatus=2 >> /etc/vim/vimrc.tiny

echo -e '\n' >> /etc/vim/vimrc
echo -e '\n' >> /etc/vim/vimrc
echo set nu >> /etc/vim/vimrc
echo set ts=4 >> /etc/vim/vimrc
echo set autoindent >> /etc/vim/vimrc
echo set hlsearch >> /etc/vim/vimrc
echo set incsearch >> /etc/vim/vimrc
echo set showmode >> /etc/vim/vimrc
echo set showcmd >> /etc/vim/vimrc
echo set showmatch >> /etc/vim/vimrc
echo set ignorecase >> /etc/vim/vimrc
echo set smartcase >> /etc/vim/vimrc
echo set hidden >> /etc/vim/vimrc
echo set mouse=a >> /etc/vim/vimrc
echo set paste >> /etc/vim/vimrc
echo set nocompatible >> /etc/vim/vimrc
echo set nobackup >> /etc/vim/vimrc
echo set noswapfile >> /etc/vim/vimrc
echo hi cursorLine cterm=bold ctermbg=DarkGray ctermfg=NONE >> /etc/vim/vimrc
echo set cursorline >> /etc/vim/vimrc
echo set ruler >> /etc/vim/vimrc
echo set wrap >> /etc/vim/vimrc
echo set linebreak >> /etc/vim/vimrc
echo set laststatus=2 >> /etc/vim/vimrc

# Debian Gnome Configuring:
su - marvin
gsettings set org.gnome.Settings last-panel 'network'
gsettings set org.gnome.system.location enabled false
gsettings set org.gnome.desktop.session idle-delay 0
gsettings set org.gnome.desktop.screensaver lock-delay 0
gsettings set org.gnome.desktop.screensaver lock-enabled false
gsettings set org.gnome.desktop.notifications show-in-lock-screen false
gsettings set org.gnome.desktop.privacy remove-old-trash-files false
gsettings set org.gnome.desktop.privacy remove-old-temp-files true
gsettings set org.gnome.desktop.privacy old-files-age 1
gsettings set org.gnome.desktop.privacy report-technical-problems false
gsettings set org.gnome.desktop.media-handling autorun-never true
gsettings set org.gnome.desktop.interface enable-animations false
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
gsettings set org.gnome.desktop.interface enable-animations false
gsettings set org.gnome.desktop.interface gtk-im-module 'fcitx5'
gsettings set org.gnome.desktop.datetime automatic-timezone true
gsettings set org.gnome.desktop.wm.preferences button-layout ':minimize,maximize,close'

gsettings set org.gnome.shell favorite-apps "['org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop', 'gnome-sy  stem-monitor.desktop', 'org.gnome.Extensions.desktop', 'org.gnome.Settings.desktop']"
gsettings set org.gnome.shell enabled-extensions "['dash-to-dock@micxgx.gmail.com', 'apps-menu@gnome-shell-extensions.gcampax.github.com', 'drive-menu@gnome-shell-extensions.gcampax.github.com']"
gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 50
gsettings set org.gnome.shell.extensions.dash-to-dock custom-theme-shrink true
gsettings set org.gnome.shell.extensions.dash-to-dock dock-position 'BOTTOM'
gsettings set org.gnome.shell.extensions.dash-to-dock click-action 'focus-minimize-or-previews'
gsettings set org.gnome.shell.extensions.dash-to-dock show-mounts-network true

gsettings set org.gnome.gnome-system-monitor show-dependencies true
gsettings set org.gnome.gnome-system-monitor network-total-in-bits true
gsettings set org.gnome.gnome-system-monitor.disktreenew col-4-visible true
gsettings set org.gnome.gnome-system-monitor.disktreenew col-4-width 0
gsettings set org.gnome.gnome-system-monitor.proctree col-2-visible true
gsettings set org.gnome.gnome-system-monitor current-tab 'resources'

gsettings set org.gnome.desktop.background picture-uri-dark ''
gsettings set org.gnome.desktop.background primary-color '#000000'
gsettings set org.gnome.desktop.background secondary-color '#000000'
gsettings set org.gnome.desktop.background color-shading-type 'solid'

gsettings set org.gtk.gtk4.Settings.FileChooser sort-directories-first true
gsettings set org.gtk.gtk4.Settings.FileChooser show-hidden true
gsettings set org.gnome.nautilus.preferences show-hidden-files true
gsettings set org.gnome.nautilus.window-state maximized true
gsettings set org.gnome.nautilus.icon-view default-zoom-level 'medium'

gsettings set org.gnome.TextEditor show-grid true
gsettings set org.gnome.TextEditor highlight-current-line true
gsettings set org.gnome.TextEditor show-map true
gsettings set org.gnome.TextEditor show-line-numbers true
gsettings set org.gnome.TextEditor style-scheme 'Oblivion'
gsettings set org.gnome.TextEditor custom-font 'Monospace 12'
gsettings set org.gnome.TextEditor wrap-text true
gsettings set org.gnome.TextEditor restore-session true
gsettings set org.gnome.TextEditor right-margin-position 100
gsettings set org.gnome.TextEditor discover-settings true

profile=$(gsettings get org.gnome.Terminal.ProfilesList default)
profile=${profile:1:-1}
gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$profile/" default-size-columns 180
gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$profile/" default-size-rows 60
gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$profile/" use-system-font false
gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$profile/" font 'Monospace 13'
gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$profile/" cursor-blink-mode 'on'
gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$profile/" use-theme-colors false
gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$profile/" background-color 'rgb(0,0,0)'
gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$profile/" foreground-color 'rgb(208,207,204)'
gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$profile/" scrollback-unlimited true

exit 0
